# Generated by Django 5.1.6 on 2025-03-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvtheque", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formation",
            name="niveau_degre",
            field=models.CharField(max_length=100),
        ),
    ]
