# Generated by Django 5.1.6 on 2025-03-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvtheque", "0002_alter_formation_niveau_degre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formation",
            name="niveau_degre",
            field=models.CharField(
                choices=[("BAC+1", "BAC+1"), ("BAC+2", "BAC+2")], max_length=100
            ),
        ),
    ]
